import images from './Images.js';

const flashcards = [
	{ image: images.states_of_mind, title: "States of Mind 1: The Farewells", artist: "Umberto Boccioni", date: "1911" },
	{ image: images.futurist_serata, title: "Sketch of a Futurist Serata in Perugia", artist: "Gerardo Dottori", date: "1914" },
	{ image: images.daughter_mother, title: "Daughter Born Without a Mother", artist: "Francis Picabia", date: "1915" },
	{ image: images.fountain, title: "Fountain", artist: "Marcel Duchamp", date: "1917" },
	{ image: images.elasticum, title: "Elasticum", artist: "Raoul Hausmann", date: "1920" },
	{ image: images.light_space_mod, title: "Light-Space-Modulator", artist: "Lazlo Moholy-Nagy", date: "1921-1930" },
	{ image: images.ballet_mecanique, title: "Ballet Mécanique", artist: "Fernand Leger", date: "1924" },
	{ image: images.towards_architecture, title: "Towards a New Architecture", artist: "Le Corbusier", date: "1923" },
	{ image: images.dymaxion, title: "Dymaxion House", artist: "Buckminster Fuller", date: "1927-1930" },
	{ image: images.geodesic, title: "Geodesic Dome Model", artist: "Buckminster Fuller", date: "1952" },
	{ image: images.third_international, title: "Monument to the Third International", artist: "Vladimir Tatlin", date: "1919" },
	{ image: images.workers_room, title: "Worker's Room", artist: "Aleksandr Rodchenko", date: "1925" },
	{ image: images.german_pavilion, title: "German Pavilion, Interior", artist: "Albert Speer", date: "1937" },
	{ image: images.rome_exhibition, title: "Photomontage at Exhibition of the Fascist Revolution, Rome", artist: "Giuseppe Terragni", date: "1932" },
	{ image: images.think_information, title: "Think / Information Machine", artist: "Charles and Ray Eames", date: "1964" },
	{ image: images.todays_home, title: "Just What is it that makes today's home so different, so appealing?", artist: "Richard Hamilton", date: "1956" },
	{ image: images.little_big_painting, title: "Little Big Painting", artist: "Roy Lichtenstein", date: "1965" },
	{ image: images.exploding_plastic, title: "Exploding Plastic Inevitable", artist: "Andy Warhol and the Velvet Underground,", date: "1966-67" },
	{ image: images.distribution_signs, title: "Distribution of Signs", artist: "Frieder Nake", date: "1965" },
	{ image: images.mondrian_experiment, title: "Mondrian Experiment", artist: "Michael Noll", date: "1965" },
	{ image: images.geometric_interference, title: "Geometric Interference", artist: "Gruppo N", date: "1962" },
	{ image: images.horizontal_movement, title: "Horizontal Movement", artist: "Jesus Rafael Soto", date: "1963" },
	{ image: images.gente_ampli2, title: "Gente Ampli2*", artist: "Waldemar Cordeiro", date: "1972" },
	{ image: images.sao_paolo, title: "Sao Paolo Pavilion", artist: "Oskar Hansen", date: "1959" },
	{ image: images.colloquy, title: "Colloquy of Mobiles", artist: "Gordon Pask", date: "1968" },
	{ image: images.random_war, title: "Random War", artist: "Charles Csuri", date: "1968" },
	{ image: images.tv_bra, title: "TV Bra for Living Sculpture", artist: "Charlotte Moorman and Nam June Paik", date: "1969" },
	{ image: images.nixon, title: "Nixon", artist: "Nam June Paik", date: "1965-2002" },
	{ image: images.hello, title: "Hello", artist: "Allan Kaprow", date: "1969" },
	{ image: images.wipe_cycle, title: "Wipe Cycle", artist: "Ira Schneider and Frank Gillette", date: "1969" },
	{ image: images.videofreex, title: "VideoFreex Media Bus", artist: "VideoFreex", date: "1971" },
	{ image: images.television_delivers, title: "Television Delivers People", artist: "Richard Serra", date: "1974" },
	{ image: images.menesunda, title: "La menesunda, restaged as Menesunda, Reloaded", artist: "Marta Minujin", date: "1965, 2019" },
	{ image: images.discontinuity, title: "Enter into Discontinuity", artist: "Raul Escari", date: "1966" },
	{ image: images.office_information, title: "Office of Information about the Vietnam War at Three Levels: The Visual Image, Text and Audio", artist: "David Lamelas", date: "1968" },
	{ image: images.movie_drome, title: "Movie Drome", artist: "Stan Van Der Beek", date: "1969" },
	{ image: images.moma_pulsa, title: "Installation at Moma", artist: "Pulsa Group", date: "1970" },
	{ image: images.snows, title: "Snows", artist: "Carolee Schneemann", date: "1967" },
	{ image: images.pepsi_pavilion, title: "Pepsi Pavilion, Osaka", artist: "E.A.T.", date: "1970" },
	{ image: images.seek, title: "SEEK", artist: "Nicholas Negroponte and the Architecture Machine Group", date: "1969-70" },
	{ image: images.moma_poll, title: "MoMA Poll", artist: "Hans Haacke", date: "1970" },
	{ image: images.vertical_roll, title: "Vertical Roll", artist: "Joan Jonas", date: "1972" },
	{ image: images.tech_transform, title: "Technology / Transformation", artist: "Dara Birnbaum", date: "1978-79" },
	{ image: images.tap_touch, title: "Tap and Touch Cinema", artist: "VALIE EXPORT", date: "1968" },
	{ image: images.free_white_21, title: "Free, White, and 21", artist: "Howardina Pindell", date: "1980" },
	{ image: images.lorna, title: "Lornaa", artist: "Lynn Hershman Leeson", date: "1979-83" },
	{ image: images.biorhythms, title: "Biorhythms", artist: "Sonya Rapoport", date: "1981" },
	{ image: images.corps_etranger, title: "Corps Etranger", artist: "Mona Hatoum", date: "1994" },
	{ image: images.floodnet, title: "Floodnet", artist: "Electronic Disturbance Theater", date: "1998" },
	{ image: images.jodi_org, title: "http://wwwwwwwww.jodi.org", artist: "Jodi.org", date: "1995" },
	{ image: images.heritage_gold, title: "Heritage Gold", artist: "Mongrel", date: "1998" },
	{ image: images.smartmom, title: "SmartMom", artist: "subRosa Collective", date: "1999" },
	{ image: images.homeless_vehicle, title: "Homeless Vehicle", artist: "Krzysztof Wodiczko", date: "1987-89" },
	{ image: images.refugee_wear, title: "Refugee Wear", artist: "Lucy Orta", date: "1998" },
	{ image: images.nomadic_plants, title: "Nomadic Plants", artist: "Gilberto Esparzas", date: "2010" },
	{ image: images.excellences_perfections, title: "Excellences and Perfections", artist: "Amalia Ulman", date: "2014" },
	{ image: images.rmb_city, title: "RMB City", artist: "Cao Fei", date: "2008-2011" },
	{ image: images.everything, title: "EverythingIEverWantedToKnow.com", artist: "MartineSyms", date: "2007" },
	{ image: images.bloemenveiling, title: "Bloemenveiling", artist: "Anna Ridler and David Pfau", date: "2019" }
]

export default flashcards;